2023-08-30 14:52:47,233 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:47,233 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:47,233 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:47,233 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:47,236 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:47,236 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:47,236 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:47,236 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:47,640 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@437] - Unexpected exception, retries exceeded. tries=4, remaining init limit=10000, connecting to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,640 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@437] - Unexpected exception, retries exceeded. tries=4, remaining init limit=10000, connecting to 0.0.0.0/0.0.0.0:2222
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,640 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@437] - Unexpected exception, retries exceeded. tries=4, remaining init limit=10000, connecting to 0.0.0.0/0.0.0.0:4444
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,640 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@437] - Unexpected exception, retries exceeded. tries=4, remaining init limit=10000, connecting to 0.0.0.0/0.0.0.0:3333
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,641 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,642 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:2222
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,642 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:4444
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:47,642 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:3333
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:3333:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:48,406 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:48,407 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:4444:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:48,407 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:2222:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:48,590 [myid:] - ERROR [main:o.a.z.s.p.FileTxnSnapLog@532] - Unable to truncate Txn log
java.io.IOException: No log files found to truncate! This could happen if you still have snapshots from an old setup or log files were deleted accidentally or dataLogDir was changed in zoo.cfg.
	at org.apache.zookeeper.server.persistence.FileTxnLog.truncate(FileTxnLog.java:478)
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.truncateLog(FileTxnSnapLog.java:520)
	at org.apache.zookeeper.server.ZKDatabase.truncateLog(ZKDatabase.java:604)
	at org.apache.zookeeper.server.quorum.Learner.syncWithLeader(Learner.java:597)
	at org.apache.zookeeper.server.quorum.LearnerTest.truncFailTest(LearnerTest.java:356)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2023-08-30 14:52:48,591 [myid:] - ERROR [main:o.a.z.s.q.Learner@600] - Not able to truncate the log 0x0
2023-08-30 14:52:48,602 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:48,602 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:49,003 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@437] - Unexpected exception, retries exceeded. tries=4, remaining init limit=10000, connecting to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:49,004 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:49,007 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:49,007 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:49,207 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@429] - Unexpected exception, connectToLeader exceeded. tries=2, remaining init limit=-2000, connecting to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:49,208 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:49,212 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@408] - [wasabi] Retry Loop 05 is called. MaxRetry : 5
2023-08-30 14:52:49,212 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@409] - [wasabi] Retry Loop 05 is called. MaxDuration : 100
2023-08-30 14:52:49,413 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@429] - Unexpected exception, connectToLeader exceeded. tries=2, remaining init limit=-2000, connecting to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 14:52:49,413 [myid:] - ERROR [LeaderConnector-0.0.0.0/0.0.0.0:1111:o.a.z.s.q.Learner$LeaderConnector@388] - Failed connect to 0.0.0.0/0.0.0.0:1111
java.io.IOException: Test injected Socket.connect() error.
	at org.apache.zookeeper.server.quorum.LearnerTest$TestLearner.sockConnect(LearnerTest.java:125)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.connectToLeader(Learner.java:419)
	at org.apache.zookeeper.server.quorum.Learner$LeaderConnector.run(Learner.java:376)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
